# Erkundung der Daten

In diesem Jupyter Notebook wird die Erkundung der Daten vorbereitet:
Für verschiedene Zeiträume und Filterkriterien soll die Anzahl Passanten pro Standort dargestellt werden.

Einerseits werden hier die pandas-Funktionen vorbereitet für die Datenabfrage und andererseits die "spec" für die Darstellung des Diagrammes.

## Vorbereiten der Daten

### Daten aus CSV laden

In [108]:
import pandas as pd

data = pd.read_csv('../daten/Gesamtdatensatz.csv')
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
0,2021-09-28T22:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.51,151,False,measured,...,47.0,30.0,17.0,47.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2021-09-28T22:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,13.51,118,False,measured,...,40.0,10.0,30.0,40.0,0.0,NaN,NaN,NaN,NaN,NaN
2,2021-09-28T22:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,13.51,203,False,measured,...,64.0,11.0,53.0,59.0,5.0,0.0,0.0,0.0,0.0,0.0
3,2021-09-28T22:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,13.51,0,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-09-28T23:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.46,19,False,measured,...,11.0,1.0,10.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134435,2025-07-30T06:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,partly-cloudy-day,14.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134436,2025-07-30T07:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134437,2025-07-30T07:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134438,2025-07-30T07:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134439,2025-07-30T07:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,16.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Nach Datumsbereich filtern

In [109]:
datum_von = '2024-01-01'
datum_bis = '2024-12-31'
data = data[(data['timestamp'] >= datum_von) & (data['timestamp'] <= datum_bis)]
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
79112,2024-01-01T00:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,partly-cloudy-night,4.0,5289,False,measured,...,1957.0,1650.0,307.0,1945.0,12.0,NaN,NaN,NaN,NaN,NaN
79113,2024-01-01T00:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,partly-cloudy-night,4.0,5284,False,measured,...,2471.0,122.0,2349.0,2468.0,3.0,NaN,NaN,NaN,NaN,NaN
79114,2024-01-01T00:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,partly-cloudy-night,4.0,3572,False,measured,...,1871.0,136.0,1735.0,1868.0,3.0,NaN,NaN,NaN,NaN,NaN
79115,2024-01-01T00:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,partly-cloudy-night,4.0,0,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79116,2024-01-01T01:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,partly-cloudy-night,4.0,1200,False,measured,...,379.0,276.0,103.0,379.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114147,2024-12-30T22:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,-3.1,29,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114148,2024-12-30T23:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,-2.0,139,False,measured,...,30.0,10.0,20.0,28.0,2.0,NaN,NaN,NaN,NaN,NaN
114149,2024-12-30T23:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,-2.0,63,False,measured,...,33.0,15.0,18.0,33.0,0.0,NaN,NaN,NaN,NaN,NaN
114150,2024-12-30T23:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,-2.0,97,False,measured,...,25.0,9.0,16.0,25.0,0.0,NaN,NaN,NaN,NaN,NaN
114151,2024-12-30T23:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,-2.0,9,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Nach Stundenbereich filtern

In [110]:
stunde_von = 14
stunde_bis = 18
stunden = pd.to_datetime(data['timestamp']).dt.hour
data = data[(stunden >= stunde_von) & (stunden <= stunde_bis)]
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
79168,2024-01-01T14:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,partly-cloudy-day,7.0,2088,False,measured,...,861.0,297.0,564.0,857.0,4.0,NaN,NaN,NaN,NaN,NaN
79169,2024-01-01T14:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,partly-cloudy-day,7.0,1909,False,measured,...,733.0,277.0,456.0,731.0,2.0,NaN,NaN,NaN,NaN,NaN
79170,2024-01-01T14:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,partly-cloudy-day,7.0,1647,False,measured,...,919.0,525.0,394.0,902.0,17.0,NaN,NaN,NaN,NaN,NaN
79171,2024-01-01T14:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,partly-cloudy-day,7.0,0,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79172,2024-01-01T15:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,partly-cloudy-day,6.0,2355,False,measured,...,912.0,278.0,634.0,901.0,11.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114127,2024-12-30T17:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,-2.0,1802,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114128,2024-12-30T18:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,-2.0,2743,False,measured,...,1213.0,414.0,799.0,1207.0,6.0,NaN,NaN,NaN,NaN,NaN
114129,2024-12-30T18:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,-2.0,2891,False,measured,...,1106.0,433.0,673.0,1104.0,2.0,NaN,NaN,NaN,NaN,NaN
114130,2024-12-30T18:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,-2.0,982,False,measured,...,441.0,206.0,235.0,440.0,1.0,NaN,NaN,NaN,NaN,NaN
114131,2024-12-30T18:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,-2.0,1203,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Nach Temperatur filtern

In [111]:
temperatur_von = 25
temperatur_bis = 30
data = data[(data['temperature'] >= temperatur_von) & (data['temperature'] <= temperatur_bis)]
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
88388,2024-04-06T15:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,clear-day,25.0,6755,False,measured,...,2841.0,1141.0,1700.0,2824.0,17.0,NaN,NaN,NaN,NaN,NaN
88389,2024-04-06T15:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,clear-day,25.0,5406,False,measured,...,2598.0,991.0,1607.0,2592.0,6.0,NaN,NaN,NaN,NaN,NaN
88390,2024-04-06T15:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,clear-day,25.0,4289,False,measured,...,2268.0,1058.0,1210.0,2249.0,19.0,NaN,NaN,NaN,NaN,NaN
88391,2024-04-06T15:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,clear-day,25.0,2149,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88392,2024-04-06T16:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,clear-day,26.0,5135,False,measured,...,2277.0,887.0,1390.0,2259.0,18.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103183,2024-09-07T17:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,clear-day,27.0,791,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103184,2024-09-07T18:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,clear-night,25.0,2379,False,measured,...,842.0,294.0,548.0,842.0,0.0,NaN,NaN,NaN,NaN,NaN
103185,2024-09-07T18:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,clear-night,25.0,2072,False,measured,...,820.0,334.0,486.0,819.0,1.0,NaN,NaN,NaN,NaN,NaN
103186,2024-09-07T18:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,clear-night,25.0,1540,False,measured,...,806.0,394.0,412.0,788.0,18.0,NaN,NaN,NaN,NaN,NaN
103187,2024-09-07T18:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,clear-night,25.0,380,False,measured,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Gruppieren und summieren der relevanten Spalten nach Standort

In [112]:
data = data.groupby(['location_name'], as_index=False)[[
    'pedestrians_count',
]].sum()
data

            location_name  pedestrians_count
0  Bahnhofstrasse (Mitte)             705130
1   Bahnhofstrasse (Nord)             567071
2    Bahnhofstrasse (Süd)             453965
3        Lintheschergasse             223586

### Spalten umbenennen als Vorbereitung für das Diagramm

In [113]:
data = data.rename(columns={
    'location_name': 'Standort',
    'pedestrians_count': 'Anzahl Passanten',
})
data

                 Standort  Anzahl Passanten
0  Bahnhofstrasse (Mitte)            705130
1   Bahnhofstrasse (Nord)            567071
2    Bahnhofstrasse (Süd)            453965
3        Lintheschergasse            223586

## Definition des Diagrammes

In [114]:
import altair as alt

bar_width = 80
bar_spacing = 0.4 * bar_width
chart_height = 400

chart = alt.Chart(data).mark_bar(size=bar_width).encode(
    x=alt.X(
        'Standort:N',
        sort=['Bahnhofstrasse (Nord)', 'Bahnhofstrasse (Mitte)', 'Bahnhofstrasse (Süd)', 'Lintheschergasse'],
    ).axis(
        labelAngle=-45,
        labelOffset=bar_width / 4,
    ), 
    y=alt.Y('Anzahl Passanten:Q').axis(
        format='~s',
        tickCount=7,
    ),
    tooltip=[
        alt.Tooltip('Anzahl Passanten', format=','),
    ],
).properties(
    width={'step': bar_width + bar_spacing},
    height=chart_height
).configure_axis(
    titleFontSize=17, 
    labelFontSize=15,
)
chart

alt.Chart(...)

## Generieren der Spec für die Darstellung des Diagrammes

In [116]:
import json

# In Dictionary umwandeln
spec = chart.to_dict()

# Dataset umbenennen in "values" für einfacheren Zugriff im Frontend
new_name = 'values'
old_name = spec['data']['name']
spec['data']['name'] = new_name
spec['datasets'][new_name] = spec['datasets'].pop(old_name)

# Spec in eine Datei schreiben
with open('erkundung.json', 'w') as f:
    json.dump(spec, f, indent=2)