# Erkundung der Daten

In diesem Jupyter Notebook wird die Erkundung der Daten vorbereitet:
Für verschiedene Zeiträume und Filterkriterien soll die Anzahl Passanten pro Standort dargestellt werden.

Einerseits werden hier die pandas-Funktionen vorbereitet für die Datenabfrage und andererseits die "spec" für die Darstellung des Diagrammes.

## Vorbereiten der Daten

### Daten aus CSV laden

In [7]:
import pandas as pd

data = pd.read_csv('../daten/Gesamtdatensatz.csv')
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
0,2021-09-28T22:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.51,151,False,measured,...,47.0,30.0,17.0,47.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2021-09-28T22:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,13.51,118,False,measured,...,40.0,10.0,30.0,40.0,0.0,NaN,NaN,NaN,NaN,NaN
2,2021-09-28T22:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,13.51,203,False,measured,...,64.0,11.0,53.0,59.0,5.0,0.0,0.0,0.0,0.0,0.0
3,2021-09-28T22:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,13.51,0,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-09-28T23:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.46,19,False,measured,...,11.0,1.0,10.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134435,2025-07-30T06:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,partly-cloudy-day,14.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134436,2025-07-30T07:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134437,2025-07-30T07:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134438,2025-07-30T07:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134439,2025-07-30T07:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,16.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Nach Datumsbereich filtern

In [8]:
datum_von = '2020-01-01'
datum_bis = '2025-12-31'
data = data[(data['timestamp'] >= datum_von) & (data['timestamp'] <= datum_bis)]
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
0,2021-09-28T22:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.51,151,False,measured,...,47.0,30.0,17.0,47.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2021-09-28T22:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,13.51,118,False,measured,...,40.0,10.0,30.0,40.0,0.0,NaN,NaN,NaN,NaN,NaN
2,2021-09-28T22:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,13.51,203,False,measured,...,64.0,11.0,53.0,59.0,5.0,0.0,0.0,0.0,0.0,0.0
3,2021-09-28T22:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,13.51,0,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-09-28T23:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.46,19,False,measured,...,11.0,1.0,10.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134435,2025-07-30T06:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,partly-cloudy-day,14.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134436,2025-07-30T07:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134437,2025-07-30T07:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134438,2025-07-30T07:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134439,2025-07-30T07:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,16.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Nach Stundenbereich filtern

In [9]:
stunde_von = 0
stunde_bis = 23
stunden = pd.to_datetime(data['timestamp']).dt.hour
data = data[(stunden >= stunde_von) & (stunden <= stunde_bis)]
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
0,2021-09-28T22:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.51,151,False,measured,...,47.0,30.0,17.0,47.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2021-09-28T22:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,13.51,118,False,measured,...,40.0,10.0,30.0,40.0,0.0,NaN,NaN,NaN,NaN,NaN
2,2021-09-28T22:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,13.51,203,False,measured,...,64.0,11.0,53.0,59.0,5.0,0.0,0.0,0.0,0.0,0.0
3,2021-09-28T22:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,13.51,0,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-09-28T23:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.46,19,False,measured,...,11.0,1.0,10.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134435,2025-07-30T06:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,partly-cloudy-day,14.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134436,2025-07-30T07:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134437,2025-07-30T07:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134438,2025-07-30T07:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134439,2025-07-30T07:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,16.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Nach Temperatur filtern

In [10]:
temperatur_von = -20
temperatur_bis = 40
data = data[(data['temperature'] >= temperatur_von) & (data['temperature'] <= temperatur_bis)]
data

,timestamp,location_id,location_name,ltr_label,rtl_label,weather_condition,temperature,pedestrians_count,unverified,collection_type,...,zone_3_pedestrians_count,zone_3_ltr_pedestrians_count,zone_3_rtl_pedestrians_count,zone_3_adult_pedestrians_count,zone_3_child_pedestrians_count,zone_99_pedestrians_count,zone_99_ltr_pedestrians_count,zone_99_rtl_pedestrians_count,zone_99_adult_pedestrians_count,zone_99_child_pedestrians_count
0,2021-09-28T22:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.51,151,False,measured,...,47.0,30.0,17.0,47.0,0.0,NaN,NaN,NaN,NaN,NaN
1,2021-09-28T22:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,13.51,118,False,measured,...,40.0,10.0,30.0,40.0,0.0,NaN,NaN,NaN,NaN,NaN
2,2021-09-28T22:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,13.51,203,False,measured,...,64.0,11.0,53.0,59.0,5.0,0.0,0.0,0.0,0.0,0.0
3,2021-09-28T22:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,13.51,0,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-09-28T23:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,13.46,19,False,measured,...,11.0,1.0,10.0,11.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134435,2025-07-30T06:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,partly-cloudy-day,14.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
134436,2025-07-30T07:00:00Z,329,Bahnhofstrasse (Mitte),Hauptbahnhof,Bürkliplatz,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134437,2025-07-30T07:00:00Z,331,Bahnhofstrasse (Nord),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134438,2025-07-30T07:00:00Z,330,Bahnhofstrasse (Süd),Bürkliplatz,Hauptbahnhof,cloudy,16.20,0,True,NaN,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
134439,2025-07-30T07:00:00Z,670,Lintheschergasse,Hauptbahnhof,Uraniastraße,cloudy,16.20,0,True,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Gruppieren und summieren der relevanten Spalten nach Standort

In [11]:
data = data.groupby(['location_name'], as_index=False)[[
    'pedestrians_count',
]].sum()
data

            location_name  pedestrians_count
0  Bahnhofstrasse (Mitte)           51214661
1   Bahnhofstrasse (Nord)           33316648
2    Bahnhofstrasse (Süd)           30223050
3        Lintheschergasse            5413080

### Spalten umbenennen als Vorbereitung für das Diagramm

In [12]:
data = data.rename(columns={
    'location_name': 'Standort',
    'pedestrians_count': 'Anzahl Passanten',
})
data

                 Standort  Anzahl Passanten
0  Bahnhofstrasse (Mitte)          51214661
1   Bahnhofstrasse (Nord)          33316648
2    Bahnhofstrasse (Süd)          30223050
3        Lintheschergasse           5413080

## Definition des Diagrammes

In [13]:
import altair as alt

bar_width = 80
bar_spacing = 0.4 * bar_width
chart_height = 400

chart = alt.Chart(data).mark_bar(size=bar_width).encode(
    x=alt.X(
        'Standort:N',
        sort=['Bahnhofstrasse (Nord)', 'Bahnhofstrasse (Mitte)', 'Bahnhofstrasse (Süd)', 'Lintheschergasse'],
    ).axis(
        labelAngle=-45,
        labelOffset=bar_width / 4,
    ), 
    y=alt.Y('Anzahl Passanten:Q').axis(
        format='~s',
        tickCount=7,
    ),
    tooltip=[
        alt.Tooltip('Anzahl Passanten', format=','),
    ],
).properties(
    width={'step': bar_width + bar_spacing},
    height=chart_height
).configure_axis(
    titleFontSize=17, 
    labelFontSize=15,
)
chart

alt.Chart(...)

## Generieren der Spec für die Darstellung des Diagrammes

In [14]:
import json

# In Dictionary umwandeln
spec = chart.to_dict()

# Dataset umbenennen in "values" für einfacheren Zugriff im Frontend
new_name = 'values'
old_name = spec['data']['name']
spec['data']['name'] = new_name
spec['datasets'][new_name] = spec['datasets'].pop(old_name)

# Spec in eine Datei schreiben
with open('erkundung.json', 'w') as f:
    json.dump(spec, f, indent=2)